### ISSUE TITLE
Animate Slide on Absolute Positioned Element

### ISSUE THREAD

**Issue by yuschick** [MingruiZhang/react-animate-mount#2]
I have an element, a navigation menu, that is has `position: absolute` style applied so that it can easily lay over all the other content. However, with this `position` it seems the library will only do the fade transition. Is there a way to still use the `slide` transition with an element that is absolutely positioned?

**Comment by MingruiZhang** [comment]
Absolutely positioned child doesn't has effect to it’s parent element. So if you have
```
<Animate >
  <div class="floating-absolute">
    ...
  </div>
</Animate>
```
Animate can't calculate its children's height. A work around would be putting absolute as parent outside
```
<div class="floating-absolute">
  <Animate >
    ...
  </Animate>
</div>
```
I think `slide` should work this way.

Let me know if this helps:) @yuschick

**Comment by yuschick** [comment]
Thanks, @MingruiZhang. I came up with the wrapper solution as well which worked out for me. Makes sense though about the absolute positioned item and the slide.

But great work on this library, it's quite helpful in my current project.
